<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Core\Sektor.DarkestDungeon.Core.Raid\Sektor.DarkestDungeon.Core.Raid.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\unity\Assets\Resources\Data\Curios\Curios.csv"
             Link="Data\Curios\Curios.csv"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\unity\Assets\Resources\Data\JsonLoot.json"
             Link="Data\JsonLoot.json"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\unity\Assets\Resources\Data\Mechanics\MapGenerator.txt"
             Link="Data\Mechanics\MapGenerator.txt"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\unity\Assets\Resources\Data\Dungeons\Crypts.bytes"
             Link="Data\Dungeons\Crypts.bytes"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>